### ISSUE TITLE
Problem compiling on Mac OS X 10.8

### ISSUE THREAD

**Issue by jawb** [jdduke/three_cpp#1]
Hi, after make I get the following messages :

Scanning dependencies of target three
[  4%] Building CXX object CMakeFiles/three.dir/three/impl/src.cpp.o
[  9%] Building CXX object CMakeFiles/three.dir/three/impl/src_extras.cpp.o
Linking CXX static library ../lib/x64/libthree.a
[  9%] Built target three
Scanning dependencies of target custom_attributes_particles
[ 13%] Building CXX object examples/CMakeFiles/custom_attributes_particles.dir/custom_attributes_particles.cpp.o
Linking CXX executable ../../bin/x64/custom_attributes_particles
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: _SDL_main, stbi_loadf_main(stbi_, int_, int_, int_, int) )
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: **\* [../bin/x64/custom_attributes_particles] Error 1
make[1]: **\* [examples/CMakeFiles/custom_attributes_particles.dir/all] Error 2
make: **\* [all] Error 2

**Comment by jdduke** [comment]
Could you provide any other details? Compiler? CMake settings? 

If you're using Xcode, my guess is that there's some SDL/SDLmain library or framework dependency that's not being properly set; I only ever tested with homebrew + SDL + makefiles on OSX.

This might provide some better insights: http://stackoverflow.com/questions/8221151/settting-up-sdl-on-mac-os-x-lion-with-xcode-4

**Comment by jawb** [comment]
No I'm not using Xcode, I'm using gcc 4.8.1, cmake 2.8.11.2, SDL 1.2, nothing tweaked .
Cmake output:

$ cmake ../ -DTHREE_HEADER_ONLY:BOOL=OFF

-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found SDL: /Library/Frameworks/SDL.framework;-framework Cocoa (found version "1.2.15")
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework
-- Found RAPID_JSON: /Users/JawB/Downloads/three_cpp-master/externals/rapidjson/include
-- Found GLEW: /usr/lib/libGLEW.a
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/JawB/Downloads/three_cpp-master/build

**Comment by jawb** [comment]
I think the following flags are missing: -lSDLmain -lSDL,

**Comment by ghost** [comment]
Just for those wondering: adding these flags to line 76 of the CMakeLists.txt fixed the problem for me on Mac OSX 10.9:

set(CMAKE_EXE_LINKER_FLAGS    "${CMAKE_EXE_LINKER_FLAGS}    ${THREE_COMMON_FLAGS} -lSDLMain -lSDL")

**Comment by jdduke** [comment]
Thanks for the update, and sorry this hasn't been truly resolved.  I've had enough issues with the stock "FindSDL.cmake" script that I should probably just include a better version, one that actually finds the proper libraries on current platforms. Or, even better, switch to premake...
