### ISSUE TITLE
THREE_GLES build

### ISSUE THREAD

**Issue by ghost** [jdduke/three_cpp#2]
is three_cpp ever meant to function without glew?

glCreateBuffer, glCreateTexture, and other vital parts of three_cpp are only defined if THREE_GLES isn't (which replaces THREE_GLEW), according to gl.hpp:63

**Comment by jdduke** [comment]
It's been a while, but I believe the THREE_GLES path was purely speculative.  That said, supporting it properly shouldn't be too difficult, more just a matter of sitting down with a GLES target and hammering out any issues.  You may even be able to just remove the "#ifndef THREE_GLES" guard before those functions in gl.hpp and it should just work... I believe I put the guard in as I wasn't sure if those functions were already defined in GLES (it appears they're not, only in WebGL).
