### ISSUE TITLE
Animation delta-time is always 0

### ISSUE THREAD

**Issue by ronj** [jdduke/three_cpp#4]
Since mElapsedTime in clock.hpp is not initialized, it is set to a random value. Because of this the delta-time calculation in anim.ipp yields incorrect results. In my case this leads to delta-time in the bound std::function to always be 0, effectively stopping all animations.

cppreference (http://en.cppreference.com/w/cpp/chrono/duration/duration) says that the default constructor of std::chrono::duration is defaulted so above behavior can be expected.

This issue can be solved by initializing mElapsedTime in the initializer list of Clock as follows: mElapsedTime( Duration::zero() ).

I hope you can find the time to incorporate a fix, otherwise I can do a pull-request. But it is a very small thing, really.

By the way: good effort on porting three.js to C++ and good use of C++11 features! Very inspirational.

**Comment by jdduke** [comment]
Thanks for the heads up!

**Comment by ronj** [comment]
That was fast, and no problem.
